// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRCqG1n1PqXar6w1vrTN8dUmeXYmHvOP8',
    appId: '1:16245339500:android:1e792508373c9ca5566f49',
    messagingSenderId: '16245339500',
    projectId: 'pocketjudge-7caec',
    databaseURL: 'https://pocketjudge-7caec-default-rtdb.firebaseio.com',
    storageBucket: 'pocketjudge-7caec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCZ9vYuZ63rdVrEhR89-owYN0LTnO_Yck',
    appId: '1:16245339500:ios:fd2f890eb8c8c482566f49',
    messagingSenderId: '16245339500',
    projectId: 'pocketjudge-7caec',
    databaseURL: 'https://pocketjudge-7caec-default-rtdb.firebaseio.com',
    storageBucket: 'pocketjudge-7caec.firebasestorage.app',
    iosBundleId: 'com.primefour.pocketJudge',
  );
}
